cxx_test(
  name = 'driver',
  srcs = [
    'TupleTest.cpp',
    'ColorTest.cpp',
    'CanvasTest.cpp',
    'MatrixTest.cpp',
  ],
  deps = [
    '//src:utils',
    '//src:tuple',
    '//src:color',
    '//src:canvas',
    '//src:matrix',
  ],
  framework = 'gtest',
)